
source 'git@git.musjoy.com:PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
platform :ios, '9.0'

target 'MJIM_Example' do
  pod 'MJIM/Socket', :path => '../'

end
